### PR TITLE
Set default value for activeRequests property to empty Array

### PR DESCRIPTION
**Pull request by maxletourneur**
I had an issue trying out this element where line 348 byutv-behaviors-jsonp.js was breaking.
`this.activeRequests.push(request);` // this.activeRequests is undefined

Fixed it by giving activeRequest a default value of an empty array.

### CODE REVIEW

**Comment by coderfin** [comment]
`When initializing a property to an object or array value, use a function to ensure that each element gets its own copy of the value, rather than having an object or array shared across all instances of the element.`

https://www.polymer-project.org/1.0/docs/devguide/properties#configure-values

Perhaps it could still be a function but return an array instead of using this._setActiveRequests([]);

A test for this use case would also be helpful.

**Comment by maxletourneur** [comment]
I updated the default value for activeRequest.

I believe your tests on activeRequest property are still valid as you test its length and specific indexes.

Thanks!

**Comment by coderfin** [comment]
This is good. Sorry I should have asked/mentioned this before but can you increment the version to 1.3.1 in the bower.json and update the readme changelog?

**Comment by maxletourneur** [comment]
Sure it's done

**Pull request merged**
